### ISSUE TITLE
Reshare button in Single Post views

### ISSUE THREAD

**Issue by tstrickland415** [imath/bp-reshare#13]
I would like to make a feature request to include the Reshare button in single post views instead of just having them appear in the activity streams. This way users would be able to reshare the current post  their viewing into the Activity stream, instead of only being able to reshare from an Activity stream

Or if there is a way to include it with PHP in our template files then any guidance would be very much appreciated

-Terrence

**Comment by gremelle** [comment]
I've been looking for a similar functionality as well.

I really hope it get's implemented :D

**Comment by imath** [comment]
It will be available in 2.0! Thanks for your feedback.

**Comment by imath** [comment]
Fixed in 2.0.0
