### ISSUE TITLE
Crashed Dashboard

### ISSUE THREAD

**Issue by Osisis** [imath/bp-reshare#14]
First let me say despite the above mentioned issue, great plugin. It's exactly what I was looking for. Unfortunately, upon activation it blanked out my admin area. The site itself is still working, I can see that the share button has been added, just can't access my admin/dashboard area. Going to delete for now in hopes that this can get fixed. Would love to be able to reactivate as soon as possible. Oh, BTW I'm using BP 2.2 and WP 4.2.2. I attempted to deactivate all of my plugins (all 8 of them) except for BP and see if that fixed the issue, but it did not.

**Comment by kishoresahoo** [comment]
I'm using this plugin, still did not get any issues. can you please tell how to produce it. Ii is working good, but some minor issues there. all codes are updated

**Comment by Beabbott** [comment]
Which version of BP and WP are you using? All I did was upload the zip into WP and then clicked activate and then the admin dashboard went all white. Did I miss something I was supposed to do? Thanks for the quick response that's it's working well for you.

**Comment by imath** [comment]
There's probably a duplicate function name. Have you tried to define WP_DEBUG to true to see what was causing the fatal ? imath

http://profiles.wordpress.org/imath
      De : Beabbott <notifications@github.com>
 À : imath/bp-reshare <bp-reshare@noreply.github.com> 
 Envoyé le : Mardi 2 juin 2015 4h45
 Objet : [bp-reshare] Crashed Dashboard (#14)
   
First let me say despite the above mentioned issue, great plugin. It's exactly what I was looking for. Unfortunately, upon activation it blanked out my admin area. The site itself is still working, I can see that the share button has been added, just can't access my admin/dashboard area. Going to delete for now in hopes that this can get fixed. Would love to be able to reactivate as soon as possible. Oh, BTW I'm using BP 2.2 and WP 4.2.2. I attempted to deactivate all of my plugins (all 8 of them) except for BP and see if that fixed the issue, but it did not. —

**Comment by Beabbott** [comment]
Of course I had not. That would have been too much like right. hahah, but now that you mention it this is what WP_DEBUG is telling me:
`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/blackx/public_html/test/wp/wp-content/plugins/bp-reshare-wp-plugin/includes/admin.php on line 59`
