### ISSUE TITLE
Show who shared my activity

### ISSUE THREAD

**Issue by vinit095** [imath/bp-reshare#18]
Hi thanks for this wonderful plugin as this is the only plugin for sharing activity on buddypress. I have only on question that "How can i show who shared on my activity by name ? like 'admin shared this activity.' "
i want to show this as Facebook does!!

Thanks in advance!!

**Comment by CeeGit** [comment]
This would be a very nice thing to add to this plugin. Plus if we could have some notifications in admin-bar plus email notifications, it would be a killer! Hopefully you'll have some time even if I know that you are really busy. Thank you very much for that plugin! Great job!

**Comment by imath** [comment]
Fxed in 2.0.0
