### ISSUE TITLE
Problem to reshare groups.

### ISSUE THREAD

**Issue by Lexique547** [imath/bp-reshare#19]
FR: J'ai trouvé un problème concernant les groups : quand on "reshare" une personne, le message à coté du pseudonyme est 'pseudo' a partagé '2e pseudo' (car j'y ai apporté une modification. En revache quand une personne "reshare" un group, seul la photo du groupe apparait. (cf. screen)
Auriez-vous une solution?

EN: I found a problem concerning the groups: when we "reshare" a person, the message next to the pseudonym is 'pseudo' shared 'nickname' (because I made a change, reverses when a person " Reshare "group, only the group picture appears (see screen)
Do you have any solution?

![capture](https://user-images.githubusercontent.com/29425760/27123746-189dc952-50ef-11e7-9156-1da4c837a45b.PNG)

![capture2](https://user-images.githubusercontent.com/29425760/27123747-189f7b30-50ef-11e7-8cd3-ae59567bea3b.PNG)

**Comment by imath** [comment]
Thanks for your report, i'll look at it soon.
