### ISSUE TITLE
A BP Reshare 1.0 Beta5 user - After upgrading to 2.0 Reshare disapperead

### ISSUE THREAD

**Issue by shay1383** [imath/bp-reshare#22]
Hi imath
First, Great plugin.
I have downloaded you plugin once via zip file from github page, and once from entrepot plugin
On both cases the reshare button doesn't show up at all.
I'm using latest version of WP and BP and it worked fine with you beta version, but with this version it has a problem.
I have noticed that it said that plugin need to upgrade my database, but i'll have to do it manually for some reason.
Please provide me a futher explanation.
And thank you for your amazing work for WP/BP users all over the globe.
Regards,
Shay.

**Comment by imath** [comment]
Hi @shay1383 

Thanks for your feedback. I've just tested with latest WordPress/BuddyPress versions (trunk), BP Reshare 1.0 and 2.0 and Entrepôt 1.2.0.

First there's an issue with the next BuddyPress Template Pack "BP Nouveau" #23. Which means if the active theme is not using the BP Legacy template pack, you should revert to BP Reshare 1.0 and use the database backup you probably did before upgrading the plugin.

From BP Reshare 1.0 to BP Reshare 2.0, a lot has evolved: 
1. The UI is mainly built using JavaScript
2. Reshares are no more duplicated activities to avoid duplicate content.
3. Notifications / Resharing an activity about a post can be done directly from the post

So 2. requires a DB Upgrade. If Entrepôt 1.2.0 is activated, its [Notification center](https://github.com/imath/entrepot/wiki/04-A-discreet-admin-notices-center#with-it) near the "Sceen Options" & "Help" tabs at the top of every Administration screen will display a new warning bringing you to the BP Reshare upgrade routines screen.

If you don't have the Entrepôt activated, you need to do the upgrade tasks manually. All callback functions for the upgrade to be completed are in this [array](https://github.com/imath/bp-reshare/blob/master/includes/upgrade.php#L206)

So it looks like it's what you've done.

For my tests i've used the Entrepôt Upgrade tool. Once the upgrade is done, everything works well for me : 
![capture](https://user-images.githubusercontent.com/1834524/32784867-4d416842-c950-11e7-9c84-454e57cb1a23.PNG)

If the active theme is using BP Legacy and you are using BuddyPress >= 2.8, as the UI is built using JavaScript, I advise you to check if there's a JavaScript error using your browser's console.

If you find one that relates to BP Reshare 2.0, please share its content here.

**Comment by shay1383** [comment]
Hi again
Thank you for quick respond
Firstly, my theme is using BP Legacy
About Entrepot, I did tried to install the plugin though it, and also through BP Reshare .ZIP file.
But on both cases it didn't work.
I want to activate the plugin by entrepot according to your instructions, but when I activate Entrepot I get this message on Plugins' Editor page:
You do not appear to have any plugins available at this time.

And when I deactivate Entrepot, Plugins Editor working again.
So, to avoid this bug, I'd like to install BP Reshare through it's .ZIP file, but I think I didn't quite get your database instructions:
"All callback functions for the upgrade to be completed are in this [array](https://github.com/imath/bp-reshare/blob/master/includes/upgrade.php#L206)"
Could you please be more specific about what should I copy and where?
Thank you and sorry for inconvenience.
Regards,
Shay.

**Comment by imath** [comment]
:) The fact Entrepôt is disabling the Plugin editor is not a bug but a feature to prevent a user to break his website.

My advice, if you are asking about what callback functions need to be used to manually upgrade would be to revert to BP Reshare 1.0.

If you absolutely want to upgrade, backup your database first then create a new function hooking ‘admin_init’ into a file of the mu-plugins folder. This function needs to use the functions that are keyed `callback` into the array i’ve linked before. Once you went to the admin and the page fully loaded. remove the file you created into the mu-plugins folder.. If you don’t see what i mean, I strongly advise you to revert to 1..0.

imath.
http://profiles.wordpress.org/imath/

**Comment by shay1383** [comment]
The reason I'm trying to move from 1.0 beta5 version it's because I'm facing many bugs on this version.
Such as 'page refreshing when reshare clicked' and also 'reshare button icon replaced when displayed in [shortcode activity](https://buddydev.com/plugins/bp-activity-shortcode/)'.
I think these problems are a matter of theme compability, because as far as I remember testing it worked fine on Twenty Seventeen theme.

issue num. 2:
If I already installed and activated the 2.0 plugin, but it didn't work, should i revert my database back from backup? or nothing was affected?

**Comment by imath** [comment]
Well, first i don't advise you to revert to beta5 but to 1.0.0 > https://github.com/imath/bp-reshare/releases/tag/1.0.0

![notices](https://camo.githubusercontent.com/c84a4cd2531660082d087f9ae914a79dec5c89c5/68747470733a2f2f636c6475702e636f6d2f4f336d756e35656b2d5a2e706e67)

Then, if having Entrepôt activated, you don't see a blue notice bubble with a 1 into it near the Dashboard __top__ tabs 'Screen options' & 'Help'  (instead of the 15 into the above screencap), then yes you should use your database backup.

If you see a blue notice bubble with a 1 into it, you can click on it and follow the instructions to upgrade BP Reshare or you can deactivate Entrepôt & BP Reshare before deleting both plugins folder and install 1.0.0, if you prefer to avoid the upgrade.

**Comment by shay1383** [comment]
I have activated bp reshare 1.0 and entrepot, but no notices show up in dashboard. not 1 or 15. simply nothing. only "screen options" & "help"

**Comment by imath** [comment]
No i was meaning under BP Reshare 2.0.0. Anyway the best now, is to remove Entrepôt and keep 1.0.0 activated. 

imath.
http://profiles.wordpress.org/imath/

**Comment by shay1383** [comment]
deactivated Entrepot, still nothing
By the way thank you for your support

**Comment by shay1383** [comment]
And I didn't understand this explanation:
"Then, if having Entrepôt activated, you don't see a blue notice bubble with a 1 into it near the Dashboard top tabs 'Screen options' & 'Help' (instead of the 15 into the above screencap), then yes you should use your database backup."

Do you mean that if I see 1 notifilication I need to restore, and if i see 15 it's ok?
The thing is that I didn't get any notifilications at all. should I restore?

**Comment by imath** [comment]
The Entrepôt plugins comes with an upgrade API, BP Reshare 2.0.0 is using. When BP Reshare 1.0.0 is upgraded to 2.0.0, BP Reshare 2.0.0 doesn’t do anything untill the upgrade routines are performed. To inform user an upgrade needs to be done Entrepôt will get from BP Reshare 2.0.0 this information and display a new notice into its notification center. Clicking on the notice will bring the user to the Upgrade screen where he’ll be able to launch the upgrade routines.

imath.
http://profiles.wordpress.org/imath/

**Comment by shay1383** [comment]
But my question is if I need to restore database according to what I told you in my last comment

**Comment by imath** [comment]
You only need to restore if the value  of the bp-reshare-version option name field is upper than 1.0.0 into the wp_options table or if you lost the reshare updates into the wp_bp_activity table.

imath.
http://profiles.wordpress.org/imath/

**Comment by shay1383** [comment]
Why this plugin is so complex? and not easy to setup?
