### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by anfeloga** [imath/bp-reshare#4]
Hi again

I'm trying this awesome plugin and I realized than after resharing an update, the original poster is not notified. I was wondering if were possible to add a notification for the user when a post made by him is made.

I noted than if this person is friend of You, You can see it on friends activity but in BuddyBar doesn't generate a notification.

Hope You consider this as an enhancement!

**Comment by gremelle** [comment]
Interested in this enhancement also, I hope it gets implemented

**Comment by manu89ft** [comment]
Any news or solutions for implement notifications??

**Comment by imath** [comment]
Notifications are now available since 2.0.0
